const router = require("express").Router()
const auth = require("../middleware/auth")
const Admin=require("../middleware/admin")
const userController=require("../app/controller/user.controller")
router.get('/all',userController.all)
router.get("/all/:id", userController.single)
router.delete("/all/:id", userController.delete)
router.patch("/all/:id",userController.editUser)
router.patch("/all/editPass/:id", userController.editPass)
router.get("/profile",auth,userController.profile)
router.post("/login",userController.login)
router.get("/logout",auth,userController.logout)
router.post("/LogoutAll",auth,userController.logoutAll)
router.post("/changeStatus",auth,userController.changeStatus)
const upload1 = require("../middleware/fileUpload")
router.post('/register',userController.register)
router.post('/upload/:id',upload1.single('img'),userController.uploadImage)
router.post('/order/:id',auth,userController.order)
module.exports = router